defmodule FragileWater.DBC.ChrRaces do
  use Ecto.Schema

  @primary_key {:id, :integer, autogenerate: false}
  schema "ChrRaces" do
    field(:flags, :integer)
    field(:faction_id, :integer)
    field(:exploration_sound_id, :integer)
    field(:male_display_id, :integer)
    field(:female_display_id, :integer)
    field(:client_prefix, :string)
    field(:mount_scale, :float)
    field(:base_language, :integer)
    field(:creature_type, :integer)
    field(:res_sickness_spell_id, :integer)
    field(:splash_sound_id, :integer)
    field(:client_file_string, :string)
    field(:cinematic_sequence_id, :integer)

    field(:name_lang_en_gb, :string)
    field(:name_lang_ko_kr, :string)
    field(:name_lang_fr_fr, :string)
    field(:name_lang_de_de, :string)
    field(:name_lang_en_cn, :string)
    field(:name_lang_en_tw, :string)
    field(:name_lang_es_es, :string)
    field(:name_lang_es_mx, :string)
    field(:name_lang_ru_ru, :string)
    field(:name_lang_ja_jp, :string)
    field(:name_lang_pt_pt, :string)
    field(:name_lang_it_it, :string)
    field(:name_lang_unknown_12, :string)
    field(:name_lang_unknown_13, :string)
    field(:name_lang_unknown_14, :string)
    field(:name_lang_unknown_15, :string)
    field(:name_lang_flags, :string)

    field(:name_female_lang_en_gb, :string)
    field(:name_female_lang_ko_kr, :string)
    field(:name_female_lang_fr_fr, :string)
    field(:name_female_lang_de_de, :string)
    field(:name_female_lang_en_cn, :string)
    field(:name_female_lang_en_tw, :string)
    field(:name_female_lang_es_es, :string)
    field(:name_female_lang_es_mx, :string)
    field(:name_female_lang_ru_ru, :string)
    field(:name_female_lang_ja_jp, :string)
    field(:name_female_lang_pt_pt, :string)
    field(:name_female_lang_it_it, :string)
    field(:name_female_lang_unknown_12, :string)
    field(:name_female_lang_unknown_13, :string)
    field(:name_female_lang_unknown_14, :string)
    field(:name_female_lang_unknown_15, :string)
    field(:name_female_lang_flags, :string)

    field(:name_male_lang_en_gb, :string)
    field(:name_male_lang_ko_kr, :string)
    field(:name_male_lang_fr_fr, :string)
    field(:name_male_lang_de_de, :string)
    field(:name_male_lang_en_cn, :string)
    field(:name_male_lang_en_tw, :string)
    field(:name_male_lang_es_es, :string)
    field(:name_male_lang_es_mx, :string)
    field(:name_male_lang_ru_ru, :string)
    field(:name_male_lang_ja_jp, :string)
    field(:name_male_lang_pt_pt, :string)
    field(:name_male_lang_it_it, :string)
    field(:name_male_lang_unknown_12, :string)
    field(:name_male_lang_unknown_13, :string)
    field(:name_male_lang_unknown_14, :string)
    field(:name_male_lang_unknown_15, :string)
    field(:name_male_lang_flags, :string)

    field(:facial_hair_customization_0, :string)
    field(:facial_hair_customization_1, :string)
    field(:hair_customization, :string)

    field(:required_expansion, :integer)
  end
end
